--- # Update CentOS servers
- hosts: all
  become: yes
  become_method: sudo
  become_user: ansible_user
  connection: ssh
  gather_facts: no

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest exclude=mysql*

    - name: install own version of 'needs-restarting'
      copy: src=files/needs-restarting.py dest=/root/needs-restarting.py mode=0700

    - name: Reboot required (Red Hat) - Step 1
      command: /root/needs-restarting.py -r
      register: reboot_required
      ignore_errors: True
      changed_when: False

    - name: Reboot required (Red Hat) - Step 2
      shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
      async: 30
      poll: 0
      ignore_errors: True
      notify:
        - waiting for server to come back after reboot
      when: reboot_required.rc == 1


#    - name: waiting for server to come back after reboot
#      local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=10 timeout=60
